model_list:
  - model_name: ultraai-dont-use
    litellm_params:
      model: ollama/phi
      api_base: https://localhost:8000
      api_key: "sk-1234"

litellm_settings:
  drop_params: True

general_settings: 

environment_variables:
